#!/usr/bin/env python3
"""Render the deterministic PROD-002 milestone dashboard from its JSON registry."""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path
from typing import Any


DEFAULT_REGISTRY = Path(__file__).resolve().parents[1] / "PROD_002_ISSUE_REGISTRY.json"
DEFAULT_OUTPUT = Path(__file__).resolve().parents[1] / "PROD_002_MILESTONE_DASHBOARD.md"


def load_registry(path: Path) -> dict[str, Any]:
    with path.open("r", encoding="utf-8") as handle:
        return json.load(handle)


def status_mark(status: str) -> str:
    return {
        "complete": "[x]",
        "fixed": "[x]",
        "planned": "[ ]",
        "open": "[ ]",
        "blocked_external": "[!]",
        "release_gate": "[!]",
        "accepted_technical_debt": "[~]",
    }.get(status, "[?]")


def percentage(value: int, total: int) -> str:
    return "0%" if total == 0 else f"{value * 100 / total:.0f}%"


def render_dashboard(registry: dict[str, Any]) -> str:
    tickets = registry["roadmap_tickets"]
    issues = registry["issues"]
    milestones = sorted(registry["milestones"], key=lambda item: item["order"])
    milestone_names = {item["id"]: item["name"] for item in milestones}
    ticket_counts = Counter(ticket["status"] for ticket in tickets)
    issue_counts = Counter(issue["status"] for issue in issues)

    lines = [
        "# Ashen Oath PROD-002 Milestone Dashboard",
        "",
        "> Generated from `PROD_002_ISSUE_REGISTRY.json`. Do not edit this file by hand; regenerate it after registry changes.",
        "> **Historical baseline only.** Current recovery outcomes, visual rejection, and release blockers are tracked in `RECOVERY_004_ISSUE_REGISTRY.json` and `RECOVERY_004_IMPLEMENTATION_STATUS.md`. A `complete` entry here does not mean the current visual acceptance gate passed.",
        "",
        f"- Last reviewed: `{registry['last_reviewed_at']}`",
        f"- Baseline commit: `{registry['last_reviewed_commit']}`",
        f"- Registry schema: `{registry['schema_version']}`",
        "- Scope: production, QA, roadmap, and release metadata only; gameplay and Web output are outside this registry.",
        "",
        "## Summary",
        "",
        "| Measure | Count |",
        "|---|---:|",
        f"| Roadmap tickets | {len(tickets)} |",
        f"| Complete | {ticket_counts['complete']} |",
        f"| Remaining planned | {ticket_counts['planned']} |",
        f"| Blocked by external prerequisite | {ticket_counts['blocked_external']} |",
        f"| Tracked issues | {len(issues)} |",
        f"| Open issues | {issue_counts['open']} |",
        f"| Accepted technical debt | {issue_counts['accepted_technical_debt']} |",
        "",
        "## Milestones",
        "",
        "| Milestone | Outcome | Complete | Remaining | Blocked | Progress |",
        "|---|---|---:|---:|---:|---:|",
    ]

    for milestone in milestones:
        scoped = [ticket for ticket in tickets if ticket["milestone"] == milestone["id"]]
        complete = sum(ticket["status"] == "complete" for ticket in scoped)
        blocked = sum(ticket["status"] == "blocked_external" for ticket in scoped)
        remaining = len(scoped) - complete
        lines.append(
            f"| `{milestone['id']}` | {milestone['name']} | {complete} | {remaining} | {blocked} | {percentage(complete, len(scoped))} |"
        )

    lines.extend([
        "",
        "## Active Issues",
        "",
        "| Status | ID | Severity | Area | Issue | Next ticket(s) |",
        "|---|---|---|---|---|---|",
    ])
    active_issues = [issue for issue in issues if issue["status"] not in {"fixed"}]
    for issue in active_issues:
        links = ", ".join(f"`{ticket}`" for ticket in issue["linked_tickets"])
        lines.append(
            f"| {status_mark(issue['status'])} `{issue['status']}` | `{issue['id']}` | {issue['severity']} | {issue['category']} | {issue['title']} | {links} |"
        )

    lines.extend([
        "",
        "## Roadmap",
        "",
        "| State | ID | Area | Ticket | Milestone |",
        "|---|---|---|---|---|",
    ])
    for milestone in milestones:
        for ticket in sorted(
            (item for item in tickets if item["milestone"] == milestone["id"]),
            key=lambda item: item["id"],
        ):
            lines.append(
                f"| {status_mark(ticket['status'])} `{ticket['status']}` | `{ticket['id']}` | {ticket['area']} | {ticket['title']} | `{ticket['milestone']}` {milestone_names[ticket['milestone']]} |"
            )

    policy = registry["release_policy"]
    lines.extend([
        "",
        "## Workflow",
        "",
        f"- Ordinary ticket: {policy['ordinary_ticket']}",
        f"- Milestone release: {policy['milestone_release']}",
        f"- Production URL: {policy['production_url']}",
        "- Registry verifier: `tools/verify_prod_002.py`.",
        "- Regenerate: `python tools/generate_prod_002_dashboard.py --write`.",
        "- Check without writing: `python tools/generate_prod_002_dashboard.py --check`.",
        "",
        "## Maintenance Rules",
        "",
        "- Update ticket status only when its acceptance evidence exists in the repository or release report.",
        "- Use `blocked_external` only for prerequisites outside the repository, such as signing hardware, platform accounts, or store access.",
        "- Keep gameplay, imported assets, Web output, and deployment state out of this registry.",
        "",
    ])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--write", action="store_true", help="write the rendered dashboard")
    parser.add_argument("--check", action="store_true", help="fail if the existing dashboard is stale")
    args = parser.parse_args()

    rendered = render_dashboard(load_registry(args.registry))
    if args.check:
        existing = args.output.read_text(encoding="utf-8") if args.output.exists() else ""
        if existing != rendered:
            print(f"PROD-002 DASHBOARD: FAIL (stale or missing: {args.output})")
            return 1
        print("PROD-002 DASHBOARD: PASS")
        return 0
    if args.write:
        args.output.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"PROD-002 DASHBOARD: WROTE {args.output}")
        return 0
    print(rendered, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
